[package]
name = "derive_debug"
version = "0.0.0"
autotests = false
edition = "2021"
publish = false

[lib]
proc-macro = true

[[bin]]
name = "debug-3"
path = "tests/03-custom-format.rs"

[[bin]]
name = "debug-4"
path = "tests/04-type-parameter.rs"

[[bin]]
name = "debug-5"
path = "tests/05-phantom-data.rs"

[[test]]
name = "tests"
path = "tests/progress.rs"

[dev-dependencies]
trybuild = { version = "1.0.108", features = ["diff"] }

[dependencies]
# "extra-traits" makes Debug and PartialEq available 
syn = { version = "2.0.106", features = ["full", "extra-traits"] }
quote = "1.0.26"
proc-macro2 = "1.0.95"
